language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true
before_install:
  - pip uninstall -y six
install:
  - pip install -U zc.buildout
  - buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/code-analysis
  - bin/nosetests
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - development@it-spir.it
